theme = "solarized-dark"

[[block]]
block = "focused_window"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
interval = 40

[[block]]
block = "disk_space"
path = "/mnt/T4"
alias = "/T4"
interval = 40

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{Mup}%"

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "sound"
step_width = 2
on_click ="amixer set Master toggle > /dev/null"

[[block]]
block = "time"
interval = 30
format = "%a %d|%m %T"

