theme = "space-villain"

[[block]]
block = "github"
interval = 300
format = "{total}G"

[[block]]
block = "custom"
command ="ht2000 /dev/hidraw0 |cut -d',' -f3,4,5 --output-delimiter=$'\n' | sed -r 's/^0+|0+$//g' | tr '\n' '|'"
interval = 2

#[icons]
#name = "none"

[icons.overrides]
cpu = "¦ "
net_up = " ^"
net_down = " v"

[[block]]
block = "disk_space"
path = "/"
alias = ""
interval = 3

[[block]]
block = "memory"
display_type = "memory"
icons = false
clickable = false
format_mem = "{mem_used_percents}%"
format_swap = "{mem_used_percents}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "eno1"

#[[block]]
#block = "sound"
#step_width = 2
#on_click ="amixer set Master toggle > /dev/null"

[[block]]
block = "time"
interval = 1
format = "%a %d|%m %T"

