theme.theme = "space-villain"

[[block]]
block = "github"
interval = 300
format = "{total}G"
hide_if_total_is_zero = true

#[[block]]
#block = "custom"
#command ="ht2000 /dev/hidraw0 |cut -d',' -f3,4,5 --output-delimiter=$'\n' | sed -r 's/^0+|0+$//g' | tr '\n' '|'"
#interval = 2

[icons.overrides]
cpu = "¦"
net_up = "^"
net_down = "v"
github = ""
net_wired = ""
time = ""

[[block]]
block = "disk_space"
path = "/"
format = ""
interval = 3

[[block]]
block = "memory"
format = "$mem_used_percents"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "eno1"

[[block]]
block = "time"
interval = 1
format = "%a %d|%m %T"

