theme.theme = "space-villain"

[[block]]
block = "github"
interval = 300
format = "$total G"
hide_if_total_is_zero = true

#[[block]]
#block = "custom"
#command ="ht2000 /dev/hidraw0 |cut -d',' -f3,4,5 --output-delimiter=$'\n' | sed -r 's/^0+|0+$//g' | tr '\n' '|'"
#interval = 2

[icons.overrides]
cpu = "¦"
net_up = "^"
net_down = "v"
github = ""
net_wired = ""
time = ""

[[block]]
block = "disk_space"
path = "/"
format = "$available.eng(w:2,force_prefix:true,p:G)"
interval = 5

[[block]]
block = "disk_space"
path = "/home"
format = "$available.eng(w:2,force_prefix:true,p:G)"
interval = 5

[[block]]
block = "memory"
format = "$mem_used_percents"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "eth0"

[[block]]
block = "time"
interval = 1
format = "$timestamp.datetime(f:'%a %d|%m %T')"

