filetype plugin on
set number
set mouse=a
set foldmethod=marker
set swapfile
set dir=~/.vim/tmp
set viminfo+=n~/.vim/viminfo
syntax enable
let g:rustfmt_autosave = 1
let g:syntastic_rust_checkers = ['cargo']
let g:deoplete#enable_at_startup = 1

"Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

set hidden
let g:racer_experimental_completer = 1

au BufRead /tmp/mutt-* set tw=72
au FileType rust nmap gd <Plug>(rust-def-vertical)

let g:ale_sign_error = '!>'
let g:ale_sign_warning = '!-'
highlight clear ALEErrorSign
highlight clear ALEWarningSign
let g:ale_lint_on_save = 1
let g:ale_lint_on_enter = 1
let g:ale_rust_cargo_use_check = 1
let g:ale_rust_cargo_check_all_targets = 1

set undodir=/tmp/.vimdid
set splitright
set splitbelow
set undofile
inoremap <C-j> <Esc>
vnoremap <C-j> <Esc>
nnoremap <up> <nop>
nnoremap <down> <nop>

nnoremap <left> :bp<CR>
nnoremap <right> :bn<CR>
nnoremap j gj
nnoremap k gk
