#!/bin/sh

if 
echo "$1" | pcregrep -q "^https?://w?w?w?.?youtube.com/watch/*"||
echo "$1" | pcregrep -q "^https?://w?w?w?.?bitchute.com/embed/*"||
echo "$1" | pcregrep -q "^https?://w?w?w?.?twitch.tv/*"; then
   "/usr/bin/mpv" ${*}
   exit 0
fi
"/usr/bin/xdg-open" ${*}
